import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, team, analytics }) {
  return (
    <html>
      <body className="p-6">
        <div className="p-10 mb-6 bg-sky-600 text-white rounded-xl">
          Parallel Routes Examples
        </div>
        <nav className="flex items-center justify-center gap-10 text-blue-600 mb-6">
          <Link href="/">Home</Link>
          <Link href="/page-views">Page Views</Link>
          <Link href="/visitors">Visitors</Link>
        </nav>
        <div className="flex gap-6">
          {team}
          {analytics}
        </div>
        {children}
      </body>
    </html>
  );
}

// export default function RootLayout({ children, analytics }) {
//   return (
//     <html>
//       <body>
//         <nav>
//           <Link href="/">Home</Link>
//           <br />
//           <Link href="/page-views">Page Views</Link>
//           <br />
//           <Link href="/visitors">Visitors</Link>
//         </nav>
//         <h1>root layout</h1>
//         {/* {children} */}
//         {analytics}
//       </body>
//     </html>
//   );
// }
